// import type { Metadata } from "next";
// import localFont from "next/font/local";
"use client";
import "./globals.css";
import { Provider } from "react-redux";
import store from "./reduxs/store";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Cycle Surgeon",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <Provider store={store}>{children}</Provider>
      </body>
    </html>
  );
}
